// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OpenApiClient.Typed.Models
{
    /// <summary>
    /// Author information
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Author : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Alternative names for the author</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AlternateNames { get; set; }
#nullable restore
#else
        public List<string> AlternateNames { get; set; }
#endif
        /// <summary>Biography information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OpenApiClient.Typed.Models.Bio? Bio { get; set; }
#nullable restore
#else
        public global::OpenApiClient.Typed.Models.Bio Bio { get; set; }
#endif
        /// <summary>Date of birth</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BirthDate { get; set; }
#nullable restore
#else
        public string BirthDate { get; set; }
#endif
        /// <summary>The created property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OpenApiClient.Typed.Models.ChangeRecord? Created { get; set; }
#nullable restore
#else
        public global::OpenApiClient.Typed.Models.ChangeRecord Created { get; set; }
#endif
        /// <summary>Date of death</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeathDate { get; set; }
#nullable restore
#else
        public string DeathDate { get; set; }
#endif
        /// <summary>Open Library author key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The last_modified property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OpenApiClient.Typed.Models.ChangeRecord? LastModified { get; set; }
#nullable restore
#else
        public global::OpenApiClient.Typed.Models.ChangeRecord LastModified { get; set; }
#endif
        /// <summary>The latest_revision property</summary>
        public int? LatestRevision { get; set; }
        /// <summary>External links</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OpenApiClient.Typed.Models.Link>? Links { get; set; }
#nullable restore
#else
        public List<global::OpenApiClient.Typed.Models.Link> Links { get; set; }
#endif
        /// <summary>Author&apos;s name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Author&apos;s personal name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PersonalName { get; set; }
#nullable restore
#else
        public string PersonalName { get; set; }
#endif
        /// <summary>Photo IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Photos { get; set; }
#nullable restore
#else
        public List<int?> Photos { get; set; }
#endif
        /// <summary>External identifiers</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OpenApiClient.Typed.Models.RemoteIds? RemoteIds { get; set; }
#nullable restore
#else
        public global::OpenApiClient.Typed.Models.RemoteIds RemoteIds { get; set; }
#endif
        /// <summary>The revision property</summary>
        public int? Revision { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenApiClient.Typed.Models.Author"/> and sets the default values.
        /// </summary>
        public Author()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OpenApiClient.Typed.Models.Author"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::OpenApiClient.Typed.Models.Author CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::OpenApiClient.Typed.Models.Author();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alternate_names", n => { AlternateNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "bio", n => { Bio = n.GetObjectValue<global::OpenApiClient.Typed.Models.Bio>(global::OpenApiClient.Typed.Models.Bio.CreateFromDiscriminatorValue); } },
                { "birth_date", n => { BirthDate = n.GetStringValue(); } },
                { "created", n => { Created = n.GetObjectValue<global::OpenApiClient.Typed.Models.ChangeRecord>(global::OpenApiClient.Typed.Models.ChangeRecord.CreateFromDiscriminatorValue); } },
                { "death_date", n => { DeathDate = n.GetStringValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "last_modified", n => { LastModified = n.GetObjectValue<global::OpenApiClient.Typed.Models.ChangeRecord>(global::OpenApiClient.Typed.Models.ChangeRecord.CreateFromDiscriminatorValue); } },
                { "latest_revision", n => { LatestRevision = n.GetIntValue(); } },
                { "links", n => { Links = n.GetCollectionOfObjectValues<global::OpenApiClient.Typed.Models.Link>(global::OpenApiClient.Typed.Models.Link.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "personal_name", n => { PersonalName = n.GetStringValue(); } },
                { "photos", n => { Photos = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "remote_ids", n => { RemoteIds = n.GetObjectValue<global::OpenApiClient.Typed.Models.RemoteIds>(global::OpenApiClient.Typed.Models.RemoteIds.CreateFromDiscriminatorValue); } },
                { "revision", n => { Revision = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("alternate_names", AlternateNames);
            writer.WriteObjectValue<global::OpenApiClient.Typed.Models.Bio>("bio", Bio);
            writer.WriteStringValue("birth_date", BirthDate);
            writer.WriteObjectValue<global::OpenApiClient.Typed.Models.ChangeRecord>("created", Created);
            writer.WriteStringValue("death_date", DeathDate);
            writer.WriteStringValue("key", Key);
            writer.WriteObjectValue<global::OpenApiClient.Typed.Models.ChangeRecord>("last_modified", LastModified);
            writer.WriteIntValue("latest_revision", LatestRevision);
            writer.WriteCollectionOfObjectValues<global::OpenApiClient.Typed.Models.Link>("links", Links);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("personal_name", PersonalName);
            writer.WriteCollectionOfPrimitiveValues<int?>("photos", Photos);
            writer.WriteObjectValue<global::OpenApiClient.Typed.Models.RemoteIds>("remote_ids", RemoteIds);
            writer.WriteIntValue("revision", Revision);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
