// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OpenApiClient.Typed.Models
{
    /// <summary>
    /// Book information
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Book : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The authors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OpenApiClient.Typed.Models.AuthorReference>? Authors { get; set; }
#nullable restore
#else
        public List<global::OpenApiClient.Typed.Models.AuthorReference> Authors { get; set; }
#endif
        /// <summary>Cover image IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Covers { get; set; }
#nullable restore
#else
        public List<int?> Covers { get; set; }
#endif
        /// <summary>The created property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OpenApiClient.Typed.Models.ChangeRecord? Created { get; set; }
#nullable restore
#else
        public global::OpenApiClient.Typed.Models.ChangeRecord Created { get; set; }
#endif
        /// <summary>Book description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The isbn_10 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Isbn10 { get; set; }
#nullable restore
#else
        public List<string> Isbn10 { get; set; }
#endif
        /// <summary>The isbn_13 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Isbn13 { get; set; }
#nullable restore
#else
        public List<string> Isbn13 { get; set; }
#endif
        /// <summary>Open Library book key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The last_modified property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OpenApiClient.Typed.Models.ChangeRecord? LastModified { get; set; }
#nullable restore
#else
        public global::OpenApiClient.Typed.Models.ChangeRecord LastModified { get; set; }
#endif
        /// <summary>The latest_revision property</summary>
        public int? LatestRevision { get; set; }
        /// <summary>Number of pages in the book</summary>
        public int? NumberOfPages { get; set; }
        /// <summary>Publication date</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublishDate { get; set; }
#nullable restore
#else
        public string PublishDate { get; set; }
#endif
        /// <summary>The publishers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Publishers { get; set; }
#nullable restore
#else
        public List<string> Publishers { get; set; }
#endif
        /// <summary>The revision property</summary>
        public int? Revision { get; set; }
        /// <summary>The subjects property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Subjects { get; set; }
#nullable restore
#else
        public List<string> Subjects { get; set; }
#endif
        /// <summary>Book subtitle</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subtitle { get; set; }
#nullable restore
#else
        public string Subtitle { get; set; }
#endif
        /// <summary>Book title</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Physical weight of the book</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Weight { get; set; }
#nullable restore
#else
        public string Weight { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::OpenApiClient.Typed.Models.Book"/> and sets the default values.
        /// </summary>
        public Book()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OpenApiClient.Typed.Models.Book"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::OpenApiClient.Typed.Models.Book CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::OpenApiClient.Typed.Models.Book();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authors", n => { Authors = n.GetCollectionOfObjectValues<global::OpenApiClient.Typed.Models.AuthorReference>(global::OpenApiClient.Typed.Models.AuthorReference.CreateFromDiscriminatorValue)?.AsList(); } },
                { "covers", n => { Covers = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "created", n => { Created = n.GetObjectValue<global::OpenApiClient.Typed.Models.ChangeRecord>(global::OpenApiClient.Typed.Models.ChangeRecord.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "isbn_10", n => { Isbn10 = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "isbn_13", n => { Isbn13 = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "last_modified", n => { LastModified = n.GetObjectValue<global::OpenApiClient.Typed.Models.ChangeRecord>(global::OpenApiClient.Typed.Models.ChangeRecord.CreateFromDiscriminatorValue); } },
                { "latest_revision", n => { LatestRevision = n.GetIntValue(); } },
                { "number_of_pages", n => { NumberOfPages = n.GetIntValue(); } },
                { "publish_date", n => { PublishDate = n.GetStringValue(); } },
                { "publishers", n => { Publishers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "revision", n => { Revision = n.GetIntValue(); } },
                { "subjects", n => { Subjects = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "subtitle", n => { Subtitle = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "weight", n => { Weight = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::OpenApiClient.Typed.Models.AuthorReference>("authors", Authors);
            writer.WriteCollectionOfPrimitiveValues<int?>("covers", Covers);
            writer.WriteObjectValue<global::OpenApiClient.Typed.Models.ChangeRecord>("created", Created);
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfPrimitiveValues<string>("isbn_10", Isbn10);
            writer.WriteCollectionOfPrimitiveValues<string>("isbn_13", Isbn13);
            writer.WriteStringValue("key", Key);
            writer.WriteObjectValue<global::OpenApiClient.Typed.Models.ChangeRecord>("last_modified", LastModified);
            writer.WriteIntValue("latest_revision", LatestRevision);
            writer.WriteIntValue("number_of_pages", NumberOfPages);
            writer.WriteStringValue("publish_date", PublishDate);
            writer.WriteCollectionOfPrimitiveValues<string>("publishers", Publishers);
            writer.WriteIntValue("revision", Revision);
            writer.WriteCollectionOfPrimitiveValues<string>("subjects", Subjects);
            writer.WriteStringValue("subtitle", Subtitle);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("weight", Weight);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
