// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using OpenApiClient.Typed.Books.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace OpenApiClient.Typed.Books
{
    /// <summary>
    /// Builds and executes requests for operations under \books
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BooksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the OpenApiClient.Typed.books.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::OpenApiClient.Typed.Books.Item.WithOlidJsonItemRequestBuilder"/></returns>
        public global::OpenApiClient.Typed.Books.Item.WithOlidJsonItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("olid", position);
                return new global::OpenApiClient.Typed.Books.Item.WithOlidJsonItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenApiClient.Typed.Books.BooksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BooksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/books", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenApiClient.Typed.Books.BooksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BooksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/books", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
