// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using OpenApiClient.Typed.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace OpenApiClient.Typed.SearchJson
{
    /// <summary>
    /// Builds and executes requests for operations under \search.json
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchJsonRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::OpenApiClient.Typed.SearchJson.SearchJsonRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchJsonRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search.json?q={q}{&limit*,page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenApiClient.Typed.SearchJson.SearchJsonRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchJsonRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search.json?q={q}{&limit*,page*}", rawUrl)
        {
        }
        /// <summary>
        /// Search for books by title, author, or other criteria. This endpoint has a PROPER SCHEMA and will generate typed models.
        /// </summary>
        /// <returns>A <see cref="global::OpenApiClient.Typed.Models.SearchResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::OpenApiClient.Typed.Models.ErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::OpenApiClient.Typed.Models.SearchResponse?> GetAsync(Action<RequestConfiguration<global::OpenApiClient.Typed.SearchJson.SearchJsonRequestBuilder.SearchJsonRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::OpenApiClient.Typed.Models.SearchResponse> GetAsync(Action<RequestConfiguration<global::OpenApiClient.Typed.SearchJson.SearchJsonRequestBuilder.SearchJsonRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::OpenApiClient.Typed.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::OpenApiClient.Typed.Models.SearchResponse>(requestInfo, global::OpenApiClient.Typed.Models.SearchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Search for books by title, author, or other criteria. This endpoint has a PROPER SCHEMA and will generate typed models.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::OpenApiClient.Typed.SearchJson.SearchJsonRequestBuilder.SearchJsonRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::OpenApiClient.Typed.SearchJson.SearchJsonRequestBuilder.SearchJsonRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::OpenApiClient.Typed.SearchJson.SearchJsonRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::OpenApiClient.Typed.SearchJson.SearchJsonRequestBuilder WithUrl(string rawUrl)
        {
            return new global::OpenApiClient.Typed.SearchJson.SearchJsonRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Search for books by title, author, or other criteria. This endpoint has a PROPER SCHEMA and will generate typed models.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SearchJsonRequestBuilderGetQueryParameters 
        {
            /// <summary>Maximum number of results to return</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Page number for pagination</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>Search query</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("q")]
            public string? Q { get; set; }
#nullable restore
#else
            [QueryParameter("q")]
            public string Q { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
