// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using OpenApiClient.Typed.Authors.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace OpenApiClient.Typed.Authors
{
    /// <summary>
    /// Builds and executes requests for operations under \authors
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthorsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the OpenApiClient.Typed.authors.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::OpenApiClient.Typed.Authors.Item.WithOlidJsonItemRequestBuilder"/></returns>
        public global::OpenApiClient.Typed.Authors.Item.WithOlidJsonItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("olid", position);
                return new global::OpenApiClient.Typed.Authors.Item.WithOlidJsonItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenApiClient.Typed.Authors.AuthorsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthorsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/authors", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenApiClient.Typed.Authors.AuthorsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthorsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/authors", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
