// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using OpenApiClient.Typed.Authors;
using OpenApiClient.Typed.Books;
using OpenApiClient.Typed.Isbn;
using OpenApiClient.Typed.SearchJson;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace OpenApiClient.Typed
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OpenApiClientTyped : BaseRequestBuilder
    {
        /// <summary>The authors property</summary>
        public global::OpenApiClient.Typed.Authors.AuthorsRequestBuilder Authors
        {
            get => new global::OpenApiClient.Typed.Authors.AuthorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The books property</summary>
        public global::OpenApiClient.Typed.Books.BooksRequestBuilder Books
        {
            get => new global::OpenApiClient.Typed.Books.BooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The isbn property</summary>
        public global::OpenApiClient.Typed.Isbn.IsbnRequestBuilder Isbn
        {
            get => new global::OpenApiClient.Typed.Isbn.IsbnRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The searchJson property</summary>
        public global::OpenApiClient.Typed.SearchJson.SearchJsonRequestBuilder SearchJson
        {
            get => new global::OpenApiClient.Typed.SearchJson.SearchJsonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenApiClient.Typed.OpenApiClientTyped"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OpenApiClientTyped(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://openlibrary.org";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
